### ISSUE TITLE
Zadania z obiektowości 

### ISSUE THREAD

**Issue by Marcin-Blok** [Marcin-Blok/Projekt-Java#30]

**Comment by leyas** [comment]
1.    Stwórz klasę Adres
a.    Klasa powinna zawierać pola: ulica, numerDomu, numerMieszkania, kodPocztowy
b.    Stwórz konstruktor umożliwiający ustawienie wszystkich pól klasy

2.    Stwórz klasy: Wykładowca oraz Student
a.    Klasy powinny zawierać prywatne pola: imie, nazwisko
b.    Stwórz konstruktor umożliwiający ustawienie wszystkich pól klasy

3.    Stwórz klasy: Ćwiczenia, Laboratoria, Wykłady
a.    Klasy powinny zawierać prywatne pola: nazwa, godzinaRozpoczecia, godzinaZakonczenia, tablica
b.    Stwórz konstruktor umożliwiający ustawienie wszystkich pól klasy
